### PR TITLE
Revert "CMake: fix linking of extractor_tests and inst_tests"

### PR DESCRIPTION
**Pull request by regehr**
Reverts google/souper#492

### CODE REVIEW

**Comment by regehr** [comment]
This is what I was getting
```
: && /usr/bin/c++  -g  -rdynamic CMakeFiles/inst_tests.dir/unittests/Inst/InstTests.cpp.o  -o inst_tests  -Wl,-rpath,/home/regehr/souper-regehr/third_party/alive2/build libsouperInfer.a libsouperInst.a libsouperExtractor.a -lgtest_main -lgtest ../third_party/alive2/build/libalive2.so libsouperInfer.a ../third_party/z3-install/lib/libz3.a libsouperInst.a libkleeExpr.a -lLLVMLTO -lLLVMPasses -lLLVMObjCARCOpts -lLLVMSymbolize -lLLVMDebugInfoPDB -lLLVMDebugInfoDWARF -lLLVMFuzzMutate -lLLVMTableGen -lLLVMDlltoolDriver -lLLVMLineEditor -lLLVMOrcJIT -lLLVMCoverage -lLLVMMIRParser -lLLVMObjectYAML -lLLVMLibDriver -lLLVMOption -lLLVMWindowsManifest -lLLVMX86Disassembler -lLLVMX86AsmParser -lLLVMX86CodeGen -lLLVMGlobalISel -lLLVMSelectionDAG -lLLVMAsmPrinter -lLLVMX86Desc -lLLVMMCDisassembler -lLLVMX86Info -lLLVMX86AsmPrinter -lLLVMX86Utils -lLLVMMCJIT -lLLVMInterpreter -lLLVMExecutionEngine -lLLVMRuntimeDyld -lLLVMCodeGen -lLLVMTarget -lLLVMCoroutines -lLLVMipo -lLLVMInstrumentation -lLLVMVectorize -lLLVMScalarOpts -lLLVMLinker -lLLVMIRReader -lLLVMAsmParser -lLLVMInstCombine -lLLVMBitWriter -lLLVMAggressiveInstCombine -lLLVMTransformUtils -lLLVMAnalysis -lLLVMProfileData -lLLVMObject -lLLVMMCParser -lLLVMMC -lLLVMDebugInfoCodeView -lLLVMDebugInfoMSF -lLLVMBitReader -lLLVMCore -lLLVMBinaryFormat -lLLVMSupport -lLLVMDemangle -lz -lrt -ldl -ltinfo -lpthread -lm -L/home/regehr/souper-regehr/third_party/llvm/Debug/lib -L /home/regehr/souper-regehr/third_party/alive2/build -lalive2 && :
../lib/Infer/InstSynthesis.cpp:178: error: undefined reference to 'souper::BuildQuery[abi:cxx11](souper::InstContext&, std::vector<souper::BlockPCMapping, std::allocator<souper::BlockPCMapping> > const&, std::vector<souper::InstMapping, std::allocator<souper::InstMapping> > const&, souper::InstMapping, std::vector<souper::Inst*, std::allocator<souper::Inst*> >*, bool)'
../lib/Infer/InstSynthesis.cpp:234: error: undefined reference to 'souper::BuildQuery[abi:cxx11](souper::InstContext&, std::vector<souper::BlockPCMapping, std::allocator<souper::BlockPCMapping> > const&, std::vector<souper::InstMapping, std::allocator<souper::InstMapping> > const&, souper::InstMapping, std::vector<souper::Inst*, std::allocator<souper::Inst*> >*, bool)'
../lib/Infer/InstSynthesis.cpp:1363: error: undefined reference to 'souper::BuildQuery[abi:cxx11](souper::InstContext&, std::vector<souper::BlockPCMapping, std::allocator<souper::BlockPCMapping> > const&, std::vector<souper::InstMapping, std::allocator<souper::InstMapping> > const&, souper::InstMapping, std::vector<souper::Inst*, std::allocator<souper::Inst*> >*, bool)'
../lib/Infer/AliveDriver.cpp:599: error: undefined reference to 'souper::ExprBuilder::getDataflowConditions(souper::Inst*)'
../lib/Infer/ExhaustiveSynthesis.cpp:449: error: undefined reference to 'souper::BuildQuery[abi:cxx11](souper::InstContext&, std::vector<souper::BlockPCMapping, std::allocator<souper::BlockPCMapping> > const&, std::vector<souper::InstMapping, std::allocator<souper::InstMapping> > const&, souper::InstMapping, std::vector<souper::Inst*, std::allocator<souper::Inst*> >*, bool)'
collect2: error: ld returned 1 exit status
[109/114] Linking CXX executable clang-souper
ninja: build stopped: subcommand failed.
```

**Comment by LebedevRI** [comment]
Any more specific failure message?

**Comment by LebedevRI** [comment]
Just to be sure, you did try purging the *souper* build dir?
(**not** the whole third_party)

**Comment by regehr** [comment]
I did a totally fresh souper build, and got that linker error

**Comment by LebedevRI** [comment]
Okay, that is saddening, i'll look how this can be resolved alternatively.

**Comment by regehr** [comment]
on what platform are you getting this linker error? I don't think any of us have seen it.

**Comment by LebedevRI** [comment]
Debian sid + llvm lld.

**Comment by regehr** [comment]
ok, it's likely lld that's the issue, none of us here use that, as far as I know.
are you using lld system wide or is there an easy way to use it just for this project?

**Comment by LebedevRI** [comment]
It's not lld issue as in lld bug.
It's likely just another bug in the build system that is not detected because of leniency of gnu's ld's.

**Comment by regehr** [comment]
yes

**Comment by LebedevRI** [comment]
Ah, ok.
I'm sure _i_ could use other linker, but i'd prefer to find a real solution.

**Comment by regehr** [comment]
I agree.
can you share the recipe for building souper using LLD? or did you switch to that linker system-wide?

**Comment by LebedevRI** [comment]
> I agree.

Great!

> or did you switch to that linker system-wide?

Yes, i have simply overridden `/usr/bin/ld` symlink to point to the lld.

**Comment by regehr** [comment]
ok, that is a brave choice. I'll give it a try later, right now I have several other broken things and do not want to add another one.

**Comment by LebedevRI** [comment]
Thanks!

**Comment by regehr** [comment]
ok good I can reproduce the link failure when using lld
hey @pranavk can you look into this? maybe try to find the commit that made lld stop working, or else see if you can adjust @LebedevRI's patch (the one reverted here) so that we can build souper using lld and also gold or gnu ld?

**Comment by pranavk** [comment]
I can reproduce the issue when using ld.lld without Roman's patch. However, I cannot reproduce the linker error that John encountered above, after Roman's patch, with any of the linker (I tried, ld.bfd, ld.gold, ld.lld).

**Comment by regehr** [comment]
what OS, @pranavk?

**Comment by pranavk** [comment]
Fedora 29. 

```
[pranavk@pranavk docs]$ /usr/bin/ld.bfd --version
GNU ld version 2.31.1-13.fc29
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

[pranavk@pranavk docs]$ /usr/bin/ld.gold --version
GNU gold (version 2.31.1-13.fc29) 1.16
Copyright (C) 2018 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.

[pranavk@pranavk docs]$ /usr/bin/ld.lld --version
LLD 7.0.1 (compatible with GNU linkers)
[pranavk@pranavk docs]$ 
```

**Comment by regehr** [comment]
thanks. I'll try again.

**Comment by regehr** [comment]
oik, I tried again and got same error
Pranav: you should go repeat this experiment on volta

**Comment by regehr** [comment]
volta is ubuntu 18.04 just like my home machine, which is where I see this problem

**Comment by pranavk** [comment]
ok. so the following patch should fix the issue: (it fixes for me)

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 6e24fed..105be7d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -329,7 +329,7 @@ set_target_properties(z3 PROPERTIES IMPORTED_IMPLIB ${Z3_LIBRARY})
 target_link_libraries(kleeExpr ${LLVM_LIBS} ${LLVM_LDFLAGS})
 target_link_libraries(souperClangTool souperExtractor souperTool ${CLANG_LIBS} ${LLVM_LIBS} ${LLVM_LDFLAGS})
 target_link_libraries(souperExtractor souperInfer souperInst kleeExpr)
-target_link_libraries(souperInfer ${LLVM_LIBS} ${LLVM_LDFLAGS} z3)
+target_link_libraries(souperInfer souperExtractor ${LLVM_LIBS} ${LLVM_LDFLAGS} z3)
```

This is same thing as I commented on #492. We should link the missing things in the original library rather than in the final executable. The final executable will automatically work if it's fixed in the original "library" target.

**Comment by regehr** [comment]
aha, I missed that part of the discussion. please submit a PR, thanks!!

**Comment by pranavk** [comment]
I commented about moving some other dependency up the chain there in #492. But the fix that I made here in above comment works along the similar lines. Okay. I will do a new PR where I re-re-vert Roman's patch and then make the above mentioned fix.

**Pull request merged**
