### PR TITLE
Fix linking for all linkers

### PR DESCRIPTION
**Pull request by pranavk**
This should fix issues observed in #495

### CODE REVIEW

**Comment by pranavk** [comment]
@LebedevRI we also need your consent on this PR (as I reverted your reverted patch).

**Comment by pranavk** [comment]
I have tested this PR on my machine - Fedora 29 with all linkers (bfd, gold, lld) and it works for me. However, it would be great if someone who can test this thing on Ubuntu 18.04 (which was problematic on 18.04) with all the linkers.

**Comment by regehr** [comment]
works for me using gold and lld on Ubuntu 18.04, I'll merge soon if nobody objects

**Comment by LebedevRI** [comment]
> @LebedevRI we also need your consent on this PR (as I reverted your reverted patch).

google cla bot is known to not work on such multi-author prs.

**Comment by regehr** [comment]
what's the solution? close this pr and one of you does another?

**Comment by LebedevRI** [comment]
> what's the solution? close this pr and one of you does another?

That bot is for the maintainer's knowledge only.
I have encountered such problems before in [google/benchmark](https://github.com/google/benchmark) repo,
and if you know that the bot is wrong, it can (and should) just be ignored.
I.e. just merge.

Thank you both!

**Comment by regehr** [comment]
sounds good
please squash, @pranavk 
thanks!

**Comment by regehr** [comment]
please squash, @pranavk

**Comment by pranavk** [comment]
squashed

**Comment by LebedevRI** [comment]
Great, it works!
@pranavk @regehr thank you!

**Pull request merged**
