### PR TITLE
null pointer derefs found in performance testing

### PR DESCRIPTION
**Pull request by jubitaneja**

### CODE REVIEW

**Comment by regehr** [comment]
please add regression tests triggering these

**Comment by zhengyangl** [comment]
This only happens when using souper functions within ValueTracking, since these information are not available in an analysis pass. However, it is all correct if we're harvesting from Souper's own pass.

**Comment by zhengyangl** [comment]
I think we may just keep another Souper branch for performance test. We need to keep the behavior of crash in master. It can tells something wrong happened when these analysis results from other passes are missing instead of silently continue and reason imprecisely.

**Comment by regehr** [comment]
LGTM, thanks

**Comment by jubitaneja** [comment]
@zhengyangl I agree, we should have these in a separate branch.

**Pull request merged**
