### PR TITLE
clean up dockerfile

### PR DESCRIPTION
**Pull request by zhengyang92**

### CODE REVIEW

**Comment by zhengyang92** [comment]
not ready for merge

**Comment by regehr** [comment]
can you also add that warning suppression flag to our main cmakelists?

**Comment by zhengyang92** [comment]
CI is passing again, ready for merge.

**Comment by zhengyang92** [comment]
The suppression flag is moved to CMakeLists.txt.

**Comment by regehr** [comment]
thanks!!

**Pull request merged**
