### PR TITLE
Print for Inst*

### PR DESCRIPTION
**Pull request by pranavk**

### CODE REVIEW

**Comment by regehr** [comment]
I don't understand adding a function that isn't used, what's the use case?

**Comment by pranavk** [comment]
pretty helpful in debugging. Otherwise, you end up doing ReplacementContext RC; RC.printInst(bla bla). But feel free to not merge if you think it's not useful. I will create a template in my IDE to accomplish this.

**Comment by regehr** [comment]
the code is fine, but if you are adding a function with no calls in our code base, you need to explain this in a comment or something

**Comment by regehr** [comment]
ping

**Comment by pranavk** [comment]
completely forgot about it. Done now.

**Comment by regehr** [comment]
lgtm thanks

**Pull request merged**
