### PR TITLE
this version of nop synthesis is still slow, but it's not that slow

### PR DESCRIPTION
**Pull request by regehr**
and it should find a nop most of the time when one exists; the
strategy is to choose up to 20 candidate nops using BFS starting from
the bottom of the LHS

### CODE REVIEW

**Comment by rsas** [comment]
What's the state of this pull request? Have you run more experiments with the BFS selection strategy?

**Comment by regehr** [comment]
I haven't!  will do that.

But in my opinion this PR isn't a throwaway. Rather, it complements the fast nop synthesis that is developing elsewhere. By limiting the number of candidates it'll stop query size from getting out of control. So I think it's something that we want.

**Comment by regehr** [comment]
Raimondas, is it OK to merge this if I promise to (later) investigate what is the proper setting for MAX_NOPS?

**Comment by rsas** [comment]
Sure, I have no objections.

**Comment by regehr** [comment]
Ok, thanks!

I can merge this with your nop branch or you can. There'll definitely be (I hope easy) conflicts.

**Pull request merged**
