### PR TITLE
Pruning with partially restricted bits and abstract input specialization

### PR DESCRIPTION
**Pull request by manasij7479**
Makes pruning 30% faster and prunes a few percent more candidates.
Subsumes some of the slower techniques.

### CODE REVIEW

**Comment by manasij7479** [comment]
WIP

**Comment by regehr** [comment]
is this ready?
if not, you should mark it as a draft pull request

**Comment by manasij7479** [comment]
This is ready for review.

**Comment by regehr** [comment]
test cases are still coming, I assume?

**Comment by manasij7479** [comment]
This technique was not effective.
Reason: restricting inputs can only make output more restricted. Pruning is done of the basis of 'unrestrictedness'.  
I was wrong about the numbers because of a bug.
Closing.

**Pull request closed without merging**
