### PR TITLE
Apply UB constraints only on the relevant Select branches

### PR DESCRIPTION
**Pull request by chenyang78**
This patch is based Raimondas's patch for addressing the issue #55.

https://github.com/rsas/souper/commit/66934ec740cb7f00d05362ed1b716b7330f6e136

One difference from the original patch is the part where we have to resolve
the issue caused by our cache mechanism, which was introduced after
the original patch.

### CODE REVIEW

**Comment by chenyang78** [comment]
Not sure what's going on, but I signed CLA a long time ago...

**Comment by regehr** [comment]
Ugh. Could it be the thing where you didn't set your email in git on the machine you're committing from?

**Comment by chenyang78** [comment]
I use the same machine as before. The config file also looks good to me:

[user]
        name = Yang Chen
        email = chenyang@cs.utah.edu

Also, I can see my email in the commit log:

$ git log
commit ddd9d1224300aedde820158eda028f08dde3cfb8
Author: Yang Chen <chenyang@cs.utah.edu>
Date:   Sat Oct 29 23:41:42 2016 -0700

**Comment by regehr** [comment]
Sounds like we can just merge-- if they want to verify they'll see that you've signed!

**Comment by chenyang78** [comment]
OK.

**Comment by regehr** [comment]
thanks guys!

**Pull request merged**
