### PR TITLE
update to LLVM 6 now that the final version has been tagged

### PR DESCRIPTION
**Pull request by regehr**
we're now patching LLVM to disable some broken optimizations that
decrease the domain of definedness of some code (this code is from Zhengyang)

finally: when nop synthesis runs into a bug, print the souper code
that triggered it

### CODE REVIEW

**Comment by regehr** [comment]
note that we do not expect the CI tests to pass for this one. Rather, once this is merged, I'll have to update our docker image, then tests will start passing again.

**Comment by regehr** [comment]
anyone have time to take a quick look before I merge?

**Comment by regehr** [comment]
Practically speaking just trust me, I've been using this branch for a while now.
To test locally, just check out my repo + branch, build and run it.

**Comment by rsas** [comment]
I mean the Docker image.

**Comment by regehr** [comment]
Ah-- I'm not sure about that since there's travis going on as well as docker. Perhaps something like this?
https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e

**Pull request merged**
