### PR TITLE
Fix bug in funnel shift dataflow analysis

### LINKED ISSUE #629: bug in dataflow analysis
```
%0:i8 = var
%1:i8 = var
%2:i8 = reservedconst
%3 = fshl %0, %1, %2
%4 = bitreverse %3
infer %4
```

./souper-interpret $SOUPER_SOLVER bug.opt -input-values=%0=0,%1=0

### PR DESCRIPTION
**Pull request by pranavk**
Fixes #629

### CODE REVIEW

**Comment by pranavk** [comment]
@manasij7479

**Comment by regehr** [comment]
Looks great but please add a regression test

**Comment by regehr** [comment]
ping

**Comment by regehr** [comment]
lgtm, thanks!

**Pull request merged**
