### PR TITLE
Update redigo/redis go module address

### PR DESCRIPTION
**Pull request by manasij7479**

### CODE REVIEW

**Comment by regehr** [comment]
this looks good. you have tested it out?

**Comment by regehr** [comment]
I think I'll leave this pending until I merge the patches for LLVM 7.0 (I already have a branch for this) since that's the next time I'll mess with the docker infrastructure

**Comment by manasij7479** [comment]
For some reason, the CI build does not run:
go get github.com/gomodule/redigo/redis
from the Dockerfile

**Comment by regehr** [comment]
right, there's a manual docker update step. it's a pain. I'll do it for LLVM 7.

**Comment by regehr** [comment]
also probably update the docker image to latest ubuntu...

**Comment by manasij7479** [comment]
Sounds good.

**Pull request closed without merging**
