### PR TITLE
Enable running of valgrind from make check

### LINKED ISSUE #119: "make check" doesn't support valgrind?
The [LLVM testing guide](http://llvm.org/docs/TestingGuide.html) says to do this to run the regression tests under Valgrind:

```
make check LIT_ARGS="-v --vg --vg-leak"
```

However this doesn't seem to work in Souper. It just runs the test suite. Probably we can just grab a bit of  makefile/lit support from LLVM and this will work. I haven't looked into it yet.

### PR DESCRIPTION
**Pull request by jeroenk**
Fixes #119 

I'm not following llvm's approach, as suggested by John; llvm achieves a similar effect through a hand-rolled Makefile in the test directory.

### CODE REVIEW

**Comment by regehr** [comment]
Very nice. Can you add a note to the README explaining how to run tests under valgrind?

**Comment by jeroenk** [comment]
Added a note to the README.

**Comment by regehr** [comment]
In this branch "make check" is working fine but the documented command line

make check LIT_ARGS="-v --vg --vg-leak"

is failing lots of testcases. I haven't looked into it, but of course my machine has valgrind installed. Anything obvious what might be going wrong? Juts a random Ubuntu 14.04 box.

**Comment by regehr** [comment]
```
regehr@regehr-M51AC:build{lit}$ make check LIT_ARGS="-vg"
[  2%] Built target profileRuntime
[  4%] Built target souperSMTLIB2
[ 28%] Built target kleeExpr
[ 30%] Built target souperInst
[ 36%] Built target souperExtractor
[ 39%] Built target souperTool
[ 41%] Built target souperKVStore
[ 43%] Built target souperParser
[ 45%] Built target souper
[ 47%] Built target parser-test
[ 91%] Built target souperPass
[ 93%] Built target souper-check
[ 95%] Built target extractor_tests
[ 97%] Built target inst_tests
[100%] Built target parser_tests
Usage: llvm-lit [options] {file-or-path}

llvm-lit: error: no such option: -g
make[3]: *** [CMakeFiles/check] Error 2
make[2]: *** [CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2
regehr@regehr-M51AC:build{lit}$ make check LIT_ARGS="--vg"
[  2%] Built target profileRuntime
[  4%] Built target souperSMTLIB2
[ 28%] Built target kleeExpr
[ 30%] Built target souperInst
[ 36%] Built target souperExtractor
[ 39%] Built target souperTool
[ 41%] Built target souperKVStore
[ 43%] Built target souperParser
[ 45%] Built target souper
[ 47%] Built target parser-test
[ 91%] Built target souperPass
[ 93%] Built target souper-check
[ 95%] Built target extractor_tests
[ 97%] Built target inst_tests
[100%] Built target parser_tests
-- Testing: 109 tests, 4 threads --
PASS: Souper :: Extractor/illegal-sext.ll (1 of 109)
FAIL: Souper :: Extractor/blockpc1.ll (2 of 109)
FAIL: Souper :: Extractor/blockpc2.ll (3 of 109)
FAIL: Souper :: Extractor/irreducible-cg.ll (4 of 109)
PASS: Souper :: Extractor/pc1.ll (5 of 109)
PASS: Souper :: Extractor/phi-1.ll (6 of 109)
PASS: Souper :: Extractor/vector-gep.ll (7 of 109)
FAIL: Souper :: Infer/div_const.opt (8 of 109)
FAIL: Souper :: Infer/haszerobyte.opt (9 of 109)
PASS: Souper :: Extractor/switch-1.ll (10 of 109)
FAIL: Souper :: Extractor/pc2.ll (11 of 109)
FAIL: Souper :: Infer/power2.opt (12 of 109)
PASS: Souper :: Infer/odd.opt (13 of 109)
FAIL: Souper :: Infer/power2b.opt (14 of 109)
PASS: Souper :: Infer/reverse.opt (15 of 109)
FAIL: Souper :: Infer/signs.opt (16 of 109)
PASS: Souper :: Infer/ub-rhs2.opt (17 of 109)
FAIL: Souper :: Infer/ub-rhs1.opt (18 of 109)
FAIL: Souper :: Infer/ub-rhs3.opt (19 of 109)
FAIL: Souper :: Infer/ub-rhs4.opt (20 of 109)
PASS: Souper :: Pass/dump-all-replacements.ll (21 of 109)
PASS: Souper :: Pass/clang-pass.c (22 of 109)
FAIL: Souper :: Pass/single-pass.ll (23 of 109)
PASS: Souper :: Pass/standard-pass.ll (24 of 109)
FAIL: Souper :: Solver/add-nsw-no-opt1.ll (25 of 109)
FAIL: Souper :: Solver/add-nsw-no-opt2.ll (26 of 109)
FAIL: Souper :: Solver/add-nsw.ll (27 of 109)
FAIL: Souper :: Solver/add-nuw-no-opt1.ll (28 of 109)
PASS: Souper :: Solver/add-nuw-no-opt2.ll (29 of 109)
PASS: Souper :: Solver/add-nuw.ll (30 of 109)
FAIL: Souper :: Pass/clang-pass-profile.c (31 of 109)
FAIL: Souper :: Solver/ashr-exact-no-opt.ll (32 of 109)
FAIL: Souper :: Solver/ashr-exact.ll (33 of 109)
FAIL: Souper :: Solver/alive-bug.ll (34 of 109)
FAIL: Souper :: Solver/bachet1.ll (35 of 109)
PASS: Souper :: Solver/blockpc_ifelse1.ll (36 of 109)
PASS: Souper :: Solver/blockpc_ifelse2.ll (37 of 109)
FAIL: Souper :: Solver/bachet2.ll (38 of 109)
FAIL: Souper :: Solver/blockpc_switch.ll (39 of 109)
PASS: Souper :: Solver/bswap.ll (40 of 109)
PASS: Souper :: Solver/bswap2.ll (41 of 109)
PASS: Souper :: Solver/bswap3.ll (42 of 109)
PASS: Souper :: Solver/bswap4.ll (43 of 109)
PASS: Souper :: Solver/ctlz.ll (44 of 109)
PASS: Souper :: Solver/ctpop.ll (45 of 109)
FAIL: Souper :: Solver/ctlz2.ll (46 of 109)
PASS: Souper :: Solver/cttz.ll (47 of 109)
FAIL: Souper :: Solver/ctpop2.ll (48 of 109)
FAIL: Souper :: Solver/cttz2.ll (49 of 109)
PASS: Souper :: Solver/div-by-zero1.ll (50 of 109)
PASS: Souper :: Solver/div-by-zero2.ll (51 of 109)
FAIL: Souper :: Solver/eggs.ll (52 of 109)
PASS: Souper :: Solver/mul-nsw1-no-opt1.ll (53 of 109)
PASS: Souper :: Solver/div-by-zero3.ll (54 of 109)
FAIL: Souper :: Solver/fermat.ll (55 of 109)
FAIL: Souper :: Solver/mul-nsw1.ll (56 of 109)
FAIL: Souper :: Solver/mul-nsw2.ll (57 of 109)
FAIL: Souper :: Solver/mul-nuw1-no-opt2.ll (58 of 109)
FAIL: Souper :: Solver/mul-nuw1.ll (59 of 109)
FAIL: Souper :: Solver/mul-nuw2.ll (60 of 109)
PASS: Souper :: Solver/pc.ll (61 of 109)
PASS: Souper :: Solver/phi-block-predicates.ll (62 of 109)
FAIL: Souper :: Solver/phi-block-predicates2.ll (63 of 109)
FAIL: Souper :: Solver/phi-ub-predicates.ll (64 of 109)
FAIL: Souper :: Solver/phi-block-predicates3.ll (65 of 109)
FAIL: Souper :: Solver/phi-ub-predicates2a.ll (66 of 109)
FAIL: Souper :: Solver/phi-ub-predicates2b.ll (67 of 109)
FAIL: Souper :: Solver/phi-ub-predicates3a.ll (68 of 109)
FAIL: Souper :: Solver/phi-ub-predicates3b.ll (69 of 109)
FAIL: Souper :: Solver/phi-ub-predicates4a.ll (70 of 109)
FAIL: Souper :: Solver/phi-ub-predicates5.ll (71 of 109)
FAIL: Souper :: Solver/mul-nuw1-no-opt1.ll (72 of 109)
FAIL: Souper :: Solver/phi-ub-predicates4b.ll (73 of 109)
FAIL: Souper :: Solver/power2.ll (74 of 109)
PASS: Souper :: Solver/sdiv-cornercase.ll (75 of 109)
FAIL: Souper :: Solver/shl-nuw-no-opt1.ll (76 of 109)
PASS: Souper :: Solver/shl-nuw.ll (77 of 109)
PASS: Souper :: Solver/srem.ll (78 of 109)
FAIL: Souper :: Solver/sub-nuw-no-opt1.ll (79 of 109)
FAIL: Souper :: Solver/sub-nsw.ll (80 of 109)
PASS: Souper :: Solver/sub-nuw-no-opt2.ll (81 of 109)
PASS: Souper :: Solver/sub-nuw.ll (82 of 109)
FAIL: Souper :: Solver/udiv-exact-no-opt.ll (83 of 109)
FAIL: Souper :: Solver/udiv-exact.ll (84 of 109)
PASS: Souper :: Solver/udiv.ll (85 of 109)
FAIL: Souper :: Tool/add-nsw-invalid.opt (86 of 109)
FAIL: Souper :: Tool/add-nsw-lgtm.opt (87 of 109)
FAIL: Souper :: Tool/blockpc-invalid-1.opt (88 of 109)
FAIL: Souper :: Solver/zeros.ll (89 of 109)
FAIL: Souper :: Tool/blockpc-invalid-2.opt (90 of 109)
FAIL: Souper :: Tool/blockpc-lgtm-1.opt (91 of 109)
PASS: Souper :: Tool/blockpc-lgtm-2.opt (92 of 109)
PASS: Souper :: Tool/blockpc-lgtm-3.opt (93 of 109)
FAIL: Souper :: Tool/blockpc-lgtm-4.opt (94 of 109)
FAIL: Souper :: Tool/infer.opt (95 of 109)
FAIL: Souper :: Tool/many-phis-1.opt (96 of 109)
PASS: Souper :: Tool/expected.ll (97 of 109)
PASS: Souper :: Tool/negate.opt (98 of 109)
PASS: Souper :: Tool/intrinsic.ll (99 of 109)
PASS: Souper :: Tool/peep1.opt (100 of 109)
PASS: Souper :: Tool/peep2.opt (101 of 109)
FAIL: Souper :: Tool/peep3.opt (102 of 109)
FAIL: Souper :: Tool/peep5.opt (103 of 109)
PASS: Souper :: Tool/unexpected1.ll (104 of 109)
PASS: Souper :: Unit/extractor_tests.ll (105 of 109)
PASS: Souper :: Tool/unexpected2.ll (106 of 109)
PASS: Souper :: Unit/inst_tests.ll (107 of 109)
PASS: Souper :: Unit/parser_tests.ll (108 of 109)
PASS: Souper :: Tool/peep4.opt (109 of 109)
Testing Time: 300.73s
********************
Failing Tests (62):
    Souper :: Extractor/blockpc1.ll
    Souper :: Extractor/blockpc2.ll
    Souper :: Extractor/irreducible-cg.ll
    Souper :: Extractor/pc2.ll
    Souper :: Infer/div_const.opt
    Souper :: Infer/haszerobyte.opt
    Souper :: Infer/power2.opt
    Souper :: Infer/power2b.opt
    Souper :: Infer/signs.opt
    Souper :: Infer/ub-rhs1.opt
    Souper :: Infer/ub-rhs3.opt
    Souper :: Infer/ub-rhs4.opt
    Souper :: Pass/clang-pass-profile.c
    Souper :: Pass/single-pass.ll
    Souper :: Solver/add-nsw-no-opt1.ll
    Souper :: Solver/add-nsw-no-opt2.ll
    Souper :: Solver/add-nsw.ll
    Souper :: Solver/add-nuw-no-opt1.ll
    Souper :: Solver/alive-bug.ll
    Souper :: Solver/ashr-exact-no-opt.ll
    Souper :: Solver/ashr-exact.ll
    Souper :: Solver/bachet1.ll
    Souper :: Solver/bachet2.ll
    Souper :: Solver/blockpc_switch.ll
    Souper :: Solver/ctlz2.ll
    Souper :: Solver/ctpop2.ll
    Souper :: Solver/cttz2.ll
    Souper :: Solver/eggs.ll
    Souper :: Solver/fermat.ll
    Souper :: Solver/mul-nsw1.ll
    Souper :: Solver/mul-nsw2.ll
    Souper :: Solver/mul-nuw1-no-opt1.ll
    Souper :: Solver/mul-nuw1-no-opt2.ll
    Souper :: Solver/mul-nuw1.ll
    Souper :: Solver/mul-nuw2.ll
    Souper :: Solver/phi-block-predicates2.ll
    Souper :: Solver/phi-block-predicates3.ll
    Souper :: Solver/phi-ub-predicates.ll
    Souper :: Solver/phi-ub-predicates2a.ll
    Souper :: Solver/phi-ub-predicates2b.ll
    Souper :: Solver/phi-ub-predicates3a.ll
    Souper :: Solver/phi-ub-predicates3b.ll
    Souper :: Solver/phi-ub-predicates4a.ll
    Souper :: Solver/phi-ub-predicates4b.ll
    Souper :: Solver/phi-ub-predicates5.ll
    Souper :: Solver/power2.ll
    Souper :: Solver/shl-nuw-no-opt1.ll
    Souper :: Solver/sub-nsw.ll
    Souper :: Solver/sub-nuw-no-opt1.ll
    Souper :: Solver/udiv-exact-no-opt.ll
    Souper :: Solver/udiv-exact.ll
    Souper :: Solver/zeros.ll
    Souper :: Tool/add-nsw-invalid.opt
    Souper :: Tool/add-nsw-lgtm.opt
    Souper :: Tool/blockpc-invalid-1.opt
    Souper :: Tool/blockpc-invalid-2.opt
    Souper :: Tool/blockpc-lgtm-1.opt
    Souper :: Tool/blockpc-lgtm-4.opt
    Souper :: Tool/infer.opt
    Souper :: Tool/many-phis-1.opt
    Souper :: Tool/peep3.opt
    Souper :: Tool/peep5.opt

  Expected Passes    : 47
  Unexpected Failures: 62
make[3]: *** [CMakeFiles/check] Error 1
make[2]: *** [CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2
```

**Comment by jeroenk** [comment]
Ok, I'm seeing protocol errors. Looks like valgrind is interfering with the invocation of the solver. I'll investigate.

**Comment by regehr** [comment]
When I ran valgrind by hand on some souper test cases, it worked fine. Is lit using the --trace-children option, I wonder?

**Comment by jeroenk** [comment]
Yes:
```self.valgrindArgs = ['valgrind', '-q', '--run-libc-freeres=no',
                                 '--tool=memcheck', '--trace-children=yes',
                                 '--error-exitcode=123']```

**Comment by regehr** [comment]
That seems to be the problem then -- the command below works fine w/o trace-children.

```
$ valgrind -q --trace-children=yes /home/regehr/f/souper-jeroen/build/souper-check -stp-path=/usr/local/bin/stp /mnt/ssd/f/souper-jeroen/test/Infer/ub-rhs4.opt | /home/regehr/f/souper-jeroen/third_party/llvm/Debug/bin/FileCheck /mnt/ssd/f/souper-jeroen/test/Infer/ub-rhs4.opt
Protocol error
FileCheck error: '-' is empty.
```

**Comment by jeroenk** [comment]
Valgrind's output for the child is ending up in the solver output file, because stderr is redirected to that file.

@pcc Is there a particular reason for redirecting stderr to that file? I believe this has been there from the very beginning.

**Comment by regehr** [comment]
I would argue that we should not be running the solvers under valgrind, these programs probably contain benign bugs we don't want to deal with running across.

**Comment by jeroenk** [comment]
Agreed, but I also think we should not fail as hard as we do when tracing children.

The proper solution here is probably to extent lit with an option that turns tracing of children off?

**Comment by regehr** [comment]
Or perhaps just --trace-children-skip=...

**Comment by jeroenk** [comment]
Something like:

```make check LIT_ARGS="--vg --vg-arg=--trace-children-skip=/Users/jketema/development/z3/build/z3"```

Does that work for you?

**Comment by jeroenk** [comment]
To clarify: lit already comes with the --vg-arg option

**Comment by regehr** [comment]
I'm fine with the --trace-children-skip solution.

**Comment by jeroenk** [comment]
I've changed the README to mention --trace-children-skip.

**Comment by pcc** [comment]
LGTM

**Pull request merged**
