### PR TITLE
Shortcut first query if there is no constants

### PR DESCRIPTION
**Pull request by zhengyangl**

### CODE REVIEW

**Comment by regehr** [comment]
can you explain this? I thought we would jump all the way to line 555

**Comment by zhengyangl** [comment]
Yes this does jump all the way to line 555.

**Comment by zhengyangl** [comment]
Besides this shortcut, I also did some reorder to avoid unnecessary initialization

**Comment by regehr** [comment]
thanks will look again after getting kids to bed

**Comment by regehr** [comment]
ok I see now, LGTM

**Pull request merged**
