### PR TITLE
Prune phi instructions by absract-interpreting LHS

### PR DESCRIPTION
**Pull request by manasij7479**

### CODE REVIEW

**Comment by regehr** [comment]
please squash

**Comment by regehr** [comment]
squash plz

**Comment by manasij7479** [comment]
Don't merge yet.
Just recalled this has some bugs, which are fixed in a different branch.
Will have to port the fixes.

**Comment by regehr** [comment]
there's gotta be a test case you can add here

**Comment by manasij7479** [comment]
Yes! :)

**Pull request closed without merging**
