### PR TITLE
Simplify KB test harness

### PR DESCRIPTION
**Pull request by manasij7479**

### CODE REVIEW

**Comment by regehr** [comment]
LGTM thanks

**Comment by pranavk** [comment]
Did you try running `./interpreter_tests` after your changes to it? It segfaults for me with your changes to test harness. Everything is fine when I revert all the latest changes to test infra (this PR and other changes #607, #589)

**Comment by manasij7479** [comment]
Weird, can't reproduce.
Please fix if possible.

**Comment by pranavk** [comment]
So,  you are saying that `./interpreter_tests` just works for you and passes ternary tests? But how's that possible given the `fshl` implementation in #589 is incorrect.

**Comment by manasij7479** [comment]
It passes because the reference implementation of fshl in
InterprterInfra.cpp is equally incorrect.

**Comment by regehr** [comment]
what's status here? has this resulted in a pull request?

**Comment by pranavk** [comment]
@manasij7479 I am using a debug LLVM build. It's possible you are not seeing the assertion failure because you are on release llvm? The segfault is actually an assertion failure.

**Comment by regehr** [comment]
well, I assume that in the future @manasij7479 will be working with debug builds so he doesn't keep doing this

**Comment by regehr** [comment]
in the meantime: please fix this, guys

**Pull request merged**
