### PR TITLE
prevent cttz, ctlz, bitreverse on bitreverse

### PR DESCRIPTION
**Pull request by pranavk**

### CODE REVIEW

**Comment by regehr** [comment]
I think you should explain this patch more, I would have imagined that doing what the title of this patch says is much simpler than this

**Comment by regehr** [comment]
like all of the other ad-hoc pruning rules are 1 or 2 lines, what's going on here?

**Comment by pranavk** [comment]
This pruning rule is different in nature from all other ad-hoc pruning rules because it depends on 2 instructions - we have to prune situations where a bitreverse result being is used by cttz, ctlz, bitreverse or ctpop instruction. Other ad-hoc pruning rules were only concerned about a single instruction (had nothing to do with uses, etc. of that instruction).

I also factored out the other code in this PR which bumped up the size of this PR slightly. All the main pruning code is in EnumerativeSynthesis.cpp

**Comment by pranavk** [comment]
What do you think about it?

**Comment by regehr** [comment]
sorry, keep trying to find time to take a closer look, maybe today!

**Comment by regehr** [comment]
LGTM thanks!

**Pull request merged**
